# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecSite', '0002_shopdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100)),
                ('topK', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='list',
        ),
    ]
