# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecSite', '0003_auto_20180509_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topk',
            name='userId',
            field=models.CharField(max_length=10),
        ),
    ]
