# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 06:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecSite', '0004_auto_20180509_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopdb',
            old_name='product_id',
            new_name='itemId',
        ),
    ]
