# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecSite', '0005_auto_20180515_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='buyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemId', models.CharField(max_length=100)),
                ('userId', models.CharField(max_length=10)),
                ('timestamp', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='shopdb',
            old_name='clothes',
            new_name='name',
        ),
    ]
