# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecSite', '0007_auto_20180515_1559'),
    ]

    operations = [
        migrations.DeleteModel(
            name='buyRecord',
        ),
    ]
